### ISSUE TITLE
(Not Really A Issue Just A Question)

### ISSUE THREAD

**Issue by PEEPPEPPEPEPPPPPPPPPPPPPPPPPP** [KeyAuth/KeyAuth-CPP-Example#25]
How could you implement a subscription check on the c++ example I seen it on the c# example but cant seem to find it on this example? Thanks.

**Comment by wnelson03** [comment]
You can do `KeyAuthApp.data.subscription` to get the first subscription the user has. Soon we'll try and make a subscriptions array in the event the user has multiple subscriptions and you want to check for a name
