### ISSUE TITLE
Access violation reading location 0x.....

### ISSUE THREAD

**Issue by WillRadford** [KeyAuth/KeyAuth-CPP-Example#29]
When Compiling the example with VS22 library_x64.lib, I get this linker error: unresolved **external symbol "public: void __cdecl KeyAuth::api::check(void)"**, Does the library need to be updated?
![image](https://user-images.githubusercontent.com/63946534/161391339-39667ae2-8bf4-4a41-818c-651184816c74.png)

**Comment by mazk5145** [comment]
Hello **WillRadFord**, Could you try these steps on your project if you still have this issue.
```MD
1: Release x64
2: try to use this lib: https://github.com/KeyAuth/KeyAuth-CPP-Example/blob/main/library_x64.lib?raw=true
3: Right Click Solution / Properties / C/C++ / Optimization / Whole Program Optimization to "NO"
4: Make sure your Platform toolset is V143 Right Click Solution / Properties / General /
```

**Comment by WillRadford** [comment]
Hi, Just retried with these steps and it compiled, however no having an issue with "Access violation reading location 0x....."
![image](https://user-images.githubusercontent.com/63946534/161600119-5580a42b-875d-4b00-9bfb-9e65baf3eba0.png)

I will rename the issue accordingly

**Comment by mazk5145** [comment]
You could try to add ```std::cout << "error: " + KeyAuthApp.data.message``` before that if error

**Comment by mazk5145** [comment]
and send us ss of that

**Comment by WillRadford** [comment]
No output in the console, here is the Exception...
![image](https://user-images.githubusercontent.com/63946534/161600973-15ca4a9d-36c3-4606-bb18-4ff484edda39.png)

**Comment by mazk5145** [comment]
Okay interesting, is it modifed project or just example?.

1: Release x64, **DON'T** Debug it just build it and then goto that folder with explorer and open it manually try runnin as admin if normal doens't work

**Comment by WillRadford** [comment]
Still Crashing at the same point... I had tried that already but thanks for the suggestion.
Its crashing when trying to access **KeyAuthApp.data.message** after login

**Comment by mazk5145** [comment]
Are you sure you have correct keyauth details?

**Comment by WillRadford** [comment]
100% Certain, I created a new user account on my application for testing. The information is definitely right because the first keyauth.init(); is working

**Comment by WillRadford** [comment]
![image](https://user-images.githubusercontent.com/63946534/161831433-f4e762dc-5680-4dea-b866-89ecf065b7d3.png)
![image](https://user-images.githubusercontent.com/63946534/161831484-72a6300e-dbdf-4d52-abc3-d9fe586a2442.png)

Update, the session isn't being validated at initialisation?

**Comment by Fonhafner** [comment]
I have the same problem and I am now at the stage of the lnk2001 error, your method that you described from above did not help me
![image](https://user-images.githubusercontent.com/90089293/161832707-146c9b9c-117a-4cfe-aaf5-500fc09429cb.png)

**Comment by Fonhafner** [comment]
It works for me perfectly on python example, but i need c++ one, and it's just doen's built (

**Comment by mazk5145** [comment]
hmm interesting

**Comment by mazk5145** [comment]
What Visual Studio Versions do you guys have?

**Comment by mazk5145** [comment]
> Update, the session isn't being validated at initialisation?

It means you haven't logged in

**Comment by WillRadford** [comment]
It is using the correct information and the default example

**Comment by Fonhafner** [comment]
downloaded visual studio today from the official website

![image](https://user-images.githubusercontent.com/90089293/161834286-5528ff98-f0cb-44ea-9e86-6d25f0d66648.png)

**Comment by mazk5145** [comment]
> It is using the correct information and the default example

![image](https://user-images.githubusercontent.com/79049205/161834618-e0b7dacf-c0d8-4046-93e3-c3e9af5fb380.png)
okay does it come before 1 = djwaiod 2 = jwid

**Comment by mazk5145** [comment]
> 

Okay interesting hmm

**Comment by mazk5145** [comment]
> downloaded visual studio today from the official website
> 
> ![image](https://user-images.githubusercontent.com/90089293/161834286-5528ff98-f0cb-44ea-9e86-6d25f0d66648.png)

Try Right Clicking Solution / Properties / C/C++ / Optimization / Whole Program Optimization to "NO"

**Comment by WillRadford** [comment]
Already Done

**Comment by mazk5145** [comment]
ye it was for [Fonhafner](https://github.com/Fonhafner)

**Comment by mazk5145** [comment]
> 

can you screen record video where you start your application and show where it breaks?

**Comment by Fonhafner** [comment]
it doesn't compile anyway ;_(
![image](https://user-images.githubusercontent.com/90089293/161835719-7f1280ec-b6e8-40b1-b8b2-ae6012cd6e13.png)

**Comment by mazk5145** [comment]
> it doesn't compile anyway ;_( ![image](https://user-images.githubusercontent.com/90089293/161835719-7f1280ec-b6e8-40b1-b8b2-ae6012cd6e13.png)

try to click Solution / Properties /Advanced / Character Set = Mutlibyte character set

**Comment by Fonhafner** [comment]
already is 
![image](https://user-images.githubusercontent.com/90089293/161836888-456d266d-66d4-4aea-806b-c25939041c49.png)

**Comment by WillRadford** [comment]
https://user-images.githubusercontent.com/63946534/161837118-8b25e0b2-cc03-4f75-a75b-d73684af82ea.mp4

**Comment by mazk5145** [comment]
okay just one second

**Comment by mazk5145** [comment]
I rebuild'ed library file and checked that everything should work https://cdn.keyauthai.com/storage/mazkdevf/library_x64.lib

**Comment by Fonhafner** [comment]
thank you so much, now it works for me.

**Comment by mazk5145** [comment]
nice

> thank you so much, now it works for me.

**Comment by WillRadford** [comment]
Just double checking the keyauth credentials with my colleague hopefully that fixes it

**Comment by mazk5145** [comment]
okay sounds good!

**Comment by WillRadford** [comment]
I have got it fixed now, thanks for support

**Comment by mazk5145** [comment]
nice and np

**Comment by mazk5145** [comment]
Solved
