### ISSUE TITLE
Trying to launch project with KeyAuth throw error C4703

### ISSUE THREAD

**Issue by MsenHeck** [KeyAuth/KeyAuth-CPP-Example#31]
1>C:\Users\admin\Music\keyauth cpp\keyauth-cpp-library-main\auth.hpp(64): error C4703: potentially uninitialized local pointer variable '<range>$L0' used

**Comment by MsenHeck** [comment]
I fixed this warning-error by adding `#pragma warning (disable: 4703)` to the lib

**Comment by mazk5145** [comment]
yea okay, Well you probably have level 4 of Compiler Warnings enabled, that can cause this.

**Comment by mazk5145** [comment]
And since its fixed i will close this.
