### ISSUE TITLE
New CPP Example Is Not Working

### ISSUE THREAD

**Issue by blackpaper666** [KeyAuth/KeyAuth-CPP-Example#32]
![image](https://user-images.githubusercontent.com/90094400/187041666-2c6f49d4-e4f8-4dce-85a8-f52f47068fe3.png)

Without editing any example code, just fill in the application name, ownerid and etc

**Comment by jabask3dd3r** [comment]
you are trying to check data when there is nothing to check, see what you tried to do is done when checking the login and so on

**Comment by jabask3dd3r** [comment]
I advise you to do 
 std::string username;
 std::string password;
 std::string key;
 std::cout << (xorstr_("\n [*] Enter name: "));
 std::cin >> username;
 std::cout << (xorstr_("\ [*] Enter password: "));
 std::cin >> password;
KeyAuthApp.login(username, password);
if (KeyAuthApp.data.success)
 { 
     //ur code here
         }
else {
   //exit or bad password message
}

**Comment by wnelson03** [comment]
Working fine on my end. make sure you're using default example with no changes. likely that issue was caused by obfuscation or some other change you made.

**Comment by InfiniteCod3** [comment]
I am having the same issue, and i am using the default example no changes
